{{- define "java-maven-build-common" -}}
- name: test
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - compile
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - org.jacoco:jacoco-maven-plugin:prepare-agent
        - '-Dmaven.test.failure.ignore=true'
        - verify
        - org.jacoco:jacoco-maven-plugin:report
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - test
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - '-Dsonar.projectKey=$(params.CODEBASEBRANCH_NAME)'
        - '-Dsonar.projectName=$(params.CODEBASEBRANCH_NAME)'
        - '-Dsonar.qualitygate.wait=true'
        - '-Dsonar.host.url=$(params.SONAR_URL)'
        - verify
        - sonar:sonar
  workspaces:
    - name: source
      workspace: shared-workspace

- name: build
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - sonar
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - clean
        - package
        - '-DskipTests=true'
  workspaces:
    - name: source
      workspace: shared-workspace

- name: get-nexus-repository-url
  taskRef:
    kind: Task
    name: get-nexus-repository-url
  runAfter:
    - build
  params:
    - name: VERSION
      value: $(tasks.get-version.results.VERSION)
    - name: NEXUS_URL
      value: $(params.NEXUS_URL)
    - name: TOOL
      value: "maven"

- name: push
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - get-nexus-repository-url
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - deploy
        - '-DskipTests=true'
        - '-DaltDeploymentRepository=nexus::default::$(tasks.get-nexus-repository-url.results.NEXUS_REPOSITORY_URL)'
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}

{{- define "java-maven-review-common" -}}
- name: compile
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - init-values
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - compile
  workspaces:
    - name: source
      workspace: shared-workspace

- name: test
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - compile
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - org.jacoco:jacoco-maven-plugin:prepare-agent
        - '-Dmaven.test.failure.ignore=true'
        - verify
        - org.jacoco:jacoco-maven-plugin:report
  workspaces:
    - name: source
      workspace: shared-workspace

# The fetch-target-branch Task will fetch the target branch during the code-review pipeline
# because the fetch-repository Task fetches only user changes.
- name: fetch-target-branch
  taskRef:
    kind: Task
    name: git-cli
  runAfter:
    - test
  params:
    - name: GIT_USER_EMAIL
      value: edp-ci@edp.ci-user
    - name: GIT_USER_NAME
      value: edp-ci
    - name: GIT_SCRIPT
      value: |
        git fetch origin $(params.targetBranch):refs/remotes/origin/$(params.targetBranch)
  workspaces:
    - name: source
      workspace: shared-workspace
    - name: ssh-directory
      workspace: ssh-creds

- name: sonar-prepare-files
  taskRef:
    kind: Task
    name: sonar-prepare-files-maven
  runAfter:
    - fetch-target-branch
  params:
    - name: CODEBASE_NAME
      value: $(params.CODEBASE_NAME)
    - name: BRANCH_NAME
      value: $(params.targetBranch)
    - name: NORMALIZED_BRANCH
      value: $(tasks.init-values.results.NORMALIZED_BRANCH)
    - name: CHANGE_NUMBER
      value: $(params.changeNumber)
    - name: PATCHSET_NUMBER
      value: $(params.patchsetNumber)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: maven
  runAfter:
    - sonar-prepare-files
  params:
    - name: MAVEN_IMAGE
      value: $(params.maven-image-version)
    - name: GOALS
      value:
        - -B
        - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
        - '-Dartifactory.releasePath=edp-maven-releases'
        - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
        - '-Dartifactory.groupPath=edp-maven-group'
        - '-Dsonar.projectKey=$(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)'
        - '-Dsonar.projectName=$(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)'
        - '-Dsonar.qualitygate.wait=true'
        - '-Dsonar.host.url=$(params.SONAR_URL)'
        - '-Dsonar.sources=$(tasks.sonar-prepare-files.results.SONAR_SOURCES)'
        - verify
        - sonar:sonar
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
