{{- define "golang-build-operator-sdk-common" -}}
- name: sast
  taskRef:
    name: sast
  runAfter:
    - get-version
  params:
    - name: reportDataProductName
      value: $(tasks.init-values.results.TENANT_NAME)
    - name: reportDataEngagementName
      value: $(params.CODEBASEBRANCH_NAME)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: test
  taskRef:
    kind: Task
    name: golang
  runAfter:
    - sast
  params:
    - name: BASE_IMAGE
      value: $(params.go-image-version)
    - name: EXTRA_COMMANDS
      value: |
        make test
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: sonarqube-scanner
  runAfter:
    - test
  params:
    - name: SONAR_HOST_URL
      value: $(params.SONAR_URL)
    - name: SONAR_PROJECT_KEY
      value: $(params.CODEBASEBRANCH_NAME)
    - name: SONAR_PROJECT_NAME
      value: $(params.CODEBASEBRANCH_NAME)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: build
  taskRef:
    kind: Task
    name: golang
  runAfter:
    - sonar
  params:
    - name: BASE_IMAGE
      value: $(params.go-image-version)
    - name: EXTRA_COMMANDS
      value: |
        make build
  workspaces:
    - name: source
      workspace: shared-workspace

- name: create-ecr-repository
  taskRef:
    kind: Task
    name: create-ecr-repository
  runAfter:
    - build
  params:
    - name: REPO_NAME
      value: "$(tasks.init-values.results.TENANT_NAME)/$(params.CODEBASE_NAME)"
{{- end -}}

{{- define "golang-review-operator-sdk-common" -}}
- name: build
  taskRef:
    kind: Task
    name: golang
  runAfter:
    - init-values
  params:
    - name: BASE_IMAGE
      value: $(params.go-image-version)
    - name: EXTRA_COMMANDS
      value: |
        make build
  workspaces:
    - name: source
      workspace: shared-workspace

- name: test
  taskRef:
    kind: Task
    name: golang
  runAfter:
    - build
  params:
    - name: BASE_IMAGE
      value: $(params.go-image-version)
    - name: EXTRA_COMMANDS
      value: |
        make test
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
