{{- define "dotnet-build-common" -}}
- name: test
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - compile
  params:
    - name: BASE_IMAGE
      value: $(params.dotnet-sdk-image-version)
    - name: EXTRA_COMMANDS
      value: |
        ls *Tests*/*.csproj | while read -r file;
            do dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover "${file}";
        done
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - test
  params:
    - name: BASE_IMAGE
      value: 'epamedp/tekton-dotnet:0.1.0-SNAPSHOT.3'
    - name: EXTRA_COMMANDS
      value: |
        slnFilename=$(ls *.sln)
        dotnet sonarscanner begin /d:sonar.host.url=$(params.SONAR_URL) \
          /d:sonar.login=${SONAR_TOKEN} \
          /d:sonar.qualitygate.wait=true \
          /k:$(params.CODEBASEBRANCH_NAME) \
          /n:$(params.CODEBASEBRANCH_NAME) \
          /d:sonar.cs.opencover.reportsPaths=./*Tests*/*.xml
        dotnet build ${sln_filename}
        dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}
  workspaces:
    - name: source
      workspace: shared-workspace

- name: get-nexus-repository-url
  taskRef:
    kind: Task
    name: get-nexus-repository-url
  runAfter:
    - sonar
  params:
    - name: VERSION
      value: $(tasks.get-version.results.VERSION)
    - name: NEXUS_URL
      value: $(params.NEXUS_URL)
    - name: TOOL
      value: "dotnet"

- name: get-nuget-token
  taskRef:
    kind: Task
    name: get-nuget-token
  runAfter:
    - get-nexus-repository-url
  params:
    - name: NEXUS_URL
      value: $(params.NEXUS_URL)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: push
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - get-nuget-token
  params:
    - name: BASE_IMAGE
      value: $(params.dotnet-sdk-image-version)
    - name: EXTRA_COMMANDS
      value: |
        set -x
        slnFilename=$(ls *.sln)
        nugetPackagesPath="/tmp/project-nupkgs/"
        dotnet pack ${slnFilename} --no-build --output ${nugetPackagesPath} "-p:PackageVersion=$(tasks.get-version.results.VERSION)"
        set +x
        nugetApiKey=$(cat $(tasks.get-nuget-token.results.NUGET_TOKEN_FILE))
        set -x
        dotnet nuget push ${nugetPackagesPath} -k ${nugetApiKey} -s $(tasks.get-nexus-repository-url.results.NEXUS_REPOSITORY_URL)/
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}

{{- define "dotnet-review-common" -}}
- name: compile
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - fetch-repository
  params:
    - name: BASE_IMAGE
      value: $(params.dotnet-sdk-image-version)
    - name: EXTRA_COMMANDS
      value: |
        slnFilename=$(ls *.sln)
        dotnet publish $slnFilename
  workspaces:
    - name: source
      workspace: shared-workspace

- name: test
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - compile
  params:
    - name: BASE_IMAGE
      value: $(params.dotnet-sdk-image-version)
    - name: EXTRA_COMMANDS
      value: |
        ls *Tests*/*.csproj | while read -r file;
            do dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover "${file}";
        done
  workspaces:
    - name: source
      workspace: shared-workspace

# The fetch-target-branch Task will fetch the target branch during the code-review pipeline
# because the fetch-repository Task fetches only user changes.
- name: fetch-target-branch
  taskRef:
    kind: Task
    name: git-cli
  runAfter:
    - test
  params:
    - name: GIT_USER_EMAIL
      value: edp-ci@edp.ci-user
    - name: GIT_USER_NAME
      value: edp-ci
    - name: GIT_SCRIPT
      value: |
        git fetch origin $(params.targetBranch):refs/remotes/origin/$(params.targetBranch)
  workspaces:
    - name: source
      workspace: shared-workspace
    - name: ssh-directory
      workspace: ssh-creds

- name: sonar-prepare-files
  taskRef:
    kind: Task
    name: sonar-prepare-files-dotnet
  runAfter:
    - fetch-target-branch
  params:
    - name: CODEBASE_NAME
      value: $(params.CODEBASE_NAME)
    - name: BRANCH_NAME
      value: $(params.targetBranch)
    - name: NORMALIZED_BRANCH
      value: $(tasks.init-values.results.NORMALIZED_BRANCH)
    - name: CHANGE_NUMBER
      value: $(params.changeNumber)
    - name: PATCHSET_NUMBER
      value: $(params.patchsetNumber)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: dotnet
  runAfter:
    - sonar-prepare-files
  params:
    - name: BASE_IMAGE
      value: 'epamedp/tekton-dotnet:0.1.0-SNAPSHOT.3'
    - name: EXTRA_COMMANDS
      value: |
        slnFilename=$(ls *.sln)
        # /d:sonar.qualitygate.wait=true \
        dotnet sonarscanner begin /d:sonar.host.url=$(params.SONAR_URL) \
          /d:sonar.login=${SONAR_TOKEN} \
          /k:$(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY) \
          /n:$(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY) \
          /d:sonar.cs.opencover.reportsPaths=$(tasks.sonar-prepare-files.results.SONAR_SOURCES)/*Tests*/*.xml
        dotnet build ${sln_filename}
        dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
