{{- define "terraform-build-common" -}}
- name: terraform-format
  taskRef:
    kind: Task
    name: terraform
  runAfter:
    - get-version
  params:
    - name: EXTRA_COMMANDS
      value: |
        if [ -f .terraform-version ]; then
            echo "[TEKTON][INFO] The '.terraform-version' file exists"
            export TFENV_TERRAFORM_VERSION=""
        else
            echo "[TEKTON][INFO] The '.terraform-version' file does not exist. Terraform version - ${TFENV_TERRAFORM_VERSION} will be used by default"
        fi
        terraform init -backend=false
        terraform fmt -check -list=true -diff
        terraform validate
  workspaces:
    - name: source
      workspace: shared-workspace

- name: terraform-lint
  taskRef:
    kind: Task
    name: terraform
  runAfter:
    - terraform-format
  params:
    - name: BASE_IMAGE
      value: 'ghcr.io/terraform-linters/tflint:v0.41.0'
    - name: EXTRA_COMMANDS
      value: |
        tflint --color
  workspaces:
    - name: source
      workspace: shared-workspace

- name: git-tag
  taskRef:
    kind: Task
    name: git-cli
  runAfter:
    - terraform-lint
  params:
    - name: GIT_USER_EMAIL
      value: edp-ci@edp.ci-user
    - name: GIT_USER_NAME
      value: edp-ci
    - name: GIT_SCRIPT
      value: |
        git tag -a "$(tasks.get-version.results.VCS_TAG)" -m "Tag is added automatically by CI user"
        git push --tags
  workspaces:
    - name: source
      workspace: shared-workspace
    - name: ssh-directory
      workspace: ssh-creds
{{- end -}}
