{{- define "python-build-common" -}}
- name: test
  taskRef:
    kind: Task
    name: python
  runAfter:
    - compile
  params:
    - name: BASE_IMAGE
      value: $(params.python-image-version)
    - name: EXTRA_COMMANDS
      value: |
        pip3 install .
        [ -f run_service.py ] && python run_service.py &
        python setup.py pytest
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: sonarqube-scanner
  runAfter:
    - test
  params:
    - name: SONAR_HOST_URL
      value: $(params.SONAR_URL)
    - name: SONAR_PROJECT_KEY
      value: $(params.CODEBASEBRANCH_NAME)
    - name: SONAR_PROJECT_NAME
      value: $(params.CODEBASEBRANCH_NAME)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: get-nexus-repository-url
  taskRef:
    kind: Task
    name: get-nexus-repository-url
  runAfter:
    - sonar
  params:
    - name: VERSION
      value: $(tasks.get-version.results.VERSION)
    - name: NEXUS_URL
      value: $(params.NEXUS_URL)
    - name: TOOL
      value: "python"

- name: push
  taskRef:
    kind: Task
    name: python
  runAfter:
    - get-nexus-repository-url
  params:
    - name: BASE_IMAGE
      value: 'python:3.8-slim'
    - name: TWINE_REPOSITORY_URL
      value: "$(tasks.get-nexus-repository-url.results.NEXUS_REPOSITORY_URL)/"
    - name: EXTRA_COMMANDS
      value: |
        pip install twine==4.0.1
        python setup.py sdist
        twine upload dist/*
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}

{{- define "python-review-common" -}}
- name: compile
  taskRef:
    kind: Task
    name: python
  runAfter:
    - init-values
  params:
    - name: BASE_IMAGE
      value: $(params.python-image-version)
    - name: EXTRA_COMMANDS
      value: |
        python setup.py clean build install --user
  workspaces:
    - name: source
      workspace: shared-workspace

- name: test
  taskRef:
    kind: Task
    name: python
  runAfter:
    - compile
  params:
    - name: BASE_IMAGE
      value: $(params.python-image-version)
    - name: EXTRA_COMMANDS
      value: |
        pip3 install .
        [ -f run_service.py ] && python run_service.py &
        python setup.py pytest
  workspaces:
    - name: source
      workspace: shared-workspace

# The fetch-target-branch Task will fetch the target branch during the code-review pipeline
# because the fetch-repository Task fetches only user changes.
- name: fetch-target-branch
  taskRef:
    kind: Task
    name: git-cli
  runAfter:
    - test
  params:
    - name: GIT_USER_EMAIL
      value: edp-ci@edp.ci-user
    - name: GIT_USER_NAME
      value: edp-ci
    - name: GIT_SCRIPT
      value: |
        git fetch origin $(params.targetBranch):refs/remotes/origin/$(params.targetBranch)
  workspaces:
    - name: source
      workspace: shared-workspace
    - name: ssh-directory
      workspace: ssh-creds

- name: sonar-prepare-files
  taskRef:
    kind: Task
    name: sonar-prepare-files-general
  runAfter:
    - fetch-target-branch
  params:
    - name: CODEBASE_NAME
      value: $(params.CODEBASE_NAME)
    - name: BRANCH_NAME
      value: $(params.targetBranch)
    - name: NORMALIZED_BRANCH
      value: $(tasks.init-values.results.NORMALIZED_BRANCH)
    - name: CHANGE_NUMBER
      value: $(params.changeNumber)
    - name: PATCHSET_NUMBER
      value: $(params.patchsetNumber)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: sonar
  taskRef:
    kind: Task
    name: sonarqube-scanner
  runAfter:
    - sonar-prepare-files
  params:
    - name: SONAR_HOST_URL
      value: $(params.SONAR_URL)
    - name: SONAR_PROJECT_KEY
      value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
    - name: SONAR_PROJECT_NAME
      value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
    - name: SONAR_SOURCES
      value: $(tasks.sonar-prepare-files.results.SONAR_SOURCES)
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
