# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- a cluster DNS wildcard name
  dnsWildCard: ""
  # -- Gerrit SSH node port
  gerritSSHPort: "30003"
