# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- Define Git Provider to be used in Pipelines. Can be gerrit (default), gitlab, github
  gitProvider: gerrit
  # -- a cluster DNS wildcard name
  dnsWildCard: ""
  # -- Gerrit SSH node port
  gerritSSHPort: "30003"

# Kaniko configuration section
kaniko:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
  # -- AWS IAM role to be used for kaniko pod service account (IRSA). Format: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE_NAME>
  roleArn: ""

github:
  # -- The GitHub host, adjust this if you run a GitHub enterprise. Default: github.com
  host: github.com
  webhook:
    # -- Existing secret which holds GitHub integration credentials: Username, Access Token, Secret String and Private SSH Key
    existingSecret: github

gitlab:
  # -- The GitLab host, adjust this if you run a GitLab enterprise. Default: gitlab.com
  host: git.epam.com
  webhook:
    # -- Existing secret which holds GitLab integration credentials: Username, Access Token, Secret String and Private SSH Key
    existingSecret: gitlab

tekton:
  # Pruner provides auto clean up feature for the Tekton resources
  pruner:
    # -- Specifies whether a cronjob should be created
    create: true
    # -- How often to clean up resources
    schedule: "0 18 * * *"
    # -- Maximum number of resources to keep while deleting removing
    keep: 1
    # -- Supported resource for auto prune is 'pipelinerun'
    resources: "pipelinerun"

# Deploy EDP Tekton Interceptor together with pipelines library
edp-tekton-interceptor:
  # -- Deploy EDP interceptor as a part of pipeline library when true. Default: true
  enabled: true

buildTool:
  go:
    cache:
      persistentVolume:
        size: 5Gi
        # -- Specifies storageClass type. If not specified, a default storageClass for go-cache volume is used
        storageClass:
