{{ if eq .Values.global.gitProvider "gitlab" }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: gitlab-listener-autotests-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['autotests']"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-lib-autotests-template

    - name: gitlab-listener-app-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['application']"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-app-template

    - name: gitlab-listener-lib-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['library'] && extensions.spec.framework != 'docker'"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-lib-autotests-template

    - name: gitlab-listener-container-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['library'] && extensions.spec.framework == 'docker'"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-app-template

    - name: gitlab-listener-code-review
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['open', 'reopen', 'update']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-review
      template:
        ref: gitlab-code-review-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
{{ end }}
