apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-version-kaniko-default
spec:
  description:
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: BRANCH_NAME
      type: string
      description: Codebasebranch name
    - name: BASE_IMAGE
      description: "The base image for the task"
      default: "alpine:3.16"
  results:
    - name: VERSION
      description: "Application version"
    - name: VCS_TAG
      description: "VCS tag"
    - name: IS_TAG
      description: "CodebaseImageStream tag"
    - name: DEPLOYABLE_MODULE_DIR
    - name: TIMESTAMP
      description: Current timestamp
  steps:
    - name: get-timestamp
      image: alpine:3.16
      script: |
        ts=$(date "+%Y%m%d-%H%M%S")
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tr -d "\n" | tee $(results.TIMESTAMP.path)

    - name: get-version
      image: $(params.BASE_IMAGE)
      env:
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
      workingDir: $(workspaces.source.path)
      script: |
        set -e

        # get current BUILD ID
        BUILD_ID=$(cat $(results.TIMESTAMP.path))

        VERSION=${BUILD_ID}-${BRANCH_NAME}

        VCS_TAG=${VERSION}
        IS_TAG=${VCS_TAG}

        echo "VCS tag - ${VCS_TAG}"
        echo "IS tag - ${IS_TAG}"

        printf "%s" "${VERSION}" > "$(results.VERSION.path)"
        printf "%s" "${VCS_TAG}" > "$(results.VCS_TAG.path)"
        printf "%s" "${IS_TAG}" > "$(results.IS_TAG.path)"

        DEPLOYABLE_MODULE_DIR="."

        printf "%s" "${DEPLOYABLE_MODULE_DIR}" > "$(results.DEPLOYABLE_MODULE_DIR.path)"
