apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cdpipeline
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
    app.edp.epam.com/pipeline: general-deployment
    app.edp.epam.com/pipelinetype: deploy
spec:
  params:
    - name: pipelineUrl
      default: https://tekton-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: CODEBASE_TAG
      description: "Codebases with a tag separated with a space."
      type: string
      default: ""
    - name: CDPIPELINE_CR
      default: ""
    - name: CDPIPELINE_STAGE
      default: ""

  tasks:
    - name: autotests
      taskRef:
        kind: Task
        name: run-quality-gate
      params:
        - name: BASE_IMAGE
          value: "bitnami/kubectl:1.25.4"
        - name: EXTRA_COMMANDS
          value:
            echo "Hello World"

    - name: promote-images
      taskRef:
        kind: Task
        name: promote-images
      runAfter:
        - autotests
      params:
        - name: CODEBASE_TAG
          value: "$(params.CODEBASE_TAG)"
        - name: CDPIPELINE_STAGE
          value: "$(params.CDPIPELINE_STAGE)"
        - name: CDPIPELINE_CR
          value: "$(params.CDPIPELINE_CR)"
