apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-create-webhook
spec:
  volumes:
    - name: github-secret
      secret:
        secretName: $(params.GitHubSecretName)

  params:
    - name: ExternalDomain
      description: "The external domain for the EventListener e.g. `$(params.EventListenerName).<PROXYIP>.nip.io`"
      default: ""
    - name: GitHubUser
      description: "The GitHub user"
      default: ""
    - name: GitHubRepo
      description: "The GitHub repo where the webhook will be created"
      default: ""
    - name: GitHubOrg
      description: "The GitHub organization where the webhook will be created"
      default: ""
    - name: GitHubSecretName
      description: "The Secret name for GitHub access token. This is always mounted and must exist"
      default: "github"
    - name: GitHubAccessTokenKey
      description: "The GitHub access token key name"
      default: "token"
    - name: GitHubSecretStringKey
      description: "The GitHub secret string key name"
      default: "secret"
    - name: GitHubDomain
      description: "The GitHub domain. Override for GitHub Enterprise"
      default: "github.com"
    - name: WebhookEvents
      description: "List of events the webhook will send notifications for"
      default: '[\"push\",\"pull_request\"]'
  steps:
    - name: create-webhook
      image: curlimages/curl:7.85.0@sha256:f4821d304c3d1fa06dcea4feb2be79f98ff012a8fa3a51943b94e333f69b0098
      volumeMounts:
        - name: github-secret
          mountPath: /var/secret
      command:
        - sh
      args:
        - -ce
        - |
          set -e
          echo "Create Webhook"
          if [ $(params.GitHubDomain) = "github.com" ];then
            curl -v -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"https://$(params.ExternalDomain)\",\"content_type\": \"json\",\"insecure_ssl\": \"0\" ,\"secret\": \"$(cat /var/secret/$(params.GitHubSecretStringKey))\"}}" -X POST -H "Authorization: Token $(cat /var/secret/$(params.GitHubAccessTokenKey))" -L https://api.github.com/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
          else
            curl -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"https://$(params.ExternalDomain)/\",\"content_type\": \"json\",\"insecure_ssl\": \"0\" ,\"secret\": \"$(cat /var/secret/$(params.GitHubSecretStringKey))\"}}" -X POST -u $(params.GitHubUser):$(cat /var/secret/$(params.GitHubAccessTokenKey)) -L https://$(params.GitHubDomain)/api/v3/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
          fi
