apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-prepare-files-maven
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: "sonarqube scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    The sonar-prepare-files-maven Task will copy the files found by git diff
    to a different folder.

  workspaces:
    - name: source
  params:
    - name: CODEBASE_NAME
      type: string
      description: Codebase name.
    - name: BRANCH_NAME
      type: string
      description: Target branch name
    - name: NORMALIZED_BRANCH
      type: string
      description: "Branch name without '/' symbols and lowercase"
    - name: CHANGE_NUMBER
      type: string
      default: ""
      description: Change number from Merge Request
    - name: PATCHSET_NUMBER
      type: string
      default: ""
      description: Patchset number from Merge Request
  results:
    - name: SONAR_PROJECT_KEY
    - name: SONAR_SOURCES
  steps:
    - name: prepare-files
      image: alpine/git:2.36.2
      workingDir: $(workspaces.source.path)
      env:
        - name: CODEBASE_NAME
          value: "$(params.CODEBASE_NAME)"
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
        - name: NORMALIZED_BRANCH
          value: "$(params.NORMALIZED_BRANCH)"
        - name: CHANGE_NUMBER
          value: "$(params.CHANGE_NUMBER)"
        - name: PATCHSET_NUMBER
          value: "$(params.PATCHSET_NUMBER)"
        - name: HOME
          value: "$(workspaces.source.path)"
      script: |
        #!/bin/sh

        set -xe
        git config --global --add safe.directory ${HOME}

        echo "[TEKTON] CODEBASE_NAME : ${CODEBASE_NAME}"
        echo "[TEKTON] BRANCH_NAME : ${BRANCH_NAME}"
        echo "[TEKTON] CHANGE_NUMBER : ${CHANGE_NUMBER}"
        echo "[TEKTON] PATCHSET_NUMBER : ${PATCHSET_NUMBER}"
        echo "[TEKTON] NORMALIZED_BRANCH : ${NORMALIZED_BRANCH}"

        SONAR_SOURCES="codereviewAnalysisRunDir"
        mkdir -p "${SONAR_SOURCES}"

        if [ -f "target" ]; then
            echo "[TEKTON][DEBUG] Project with usual structure"
            export LANG=en_US.utf-8
            git config --local core.quotepath false
            IFS=$'\n'
            for i in $(git diff --diff-filter=ACMR --name-only origin/"${BRANCH_NAME}")
                do cp --parents "$i" "${SONAR_SOURCES}"/
                echo "file for scanner:" "$i"/
            done
            cp -f pom.xml "${SONAR_SOURCES}"/
            [ -d "src/test/" ] &&  cp --parents -r src/test/ "${SONAR_SOURCES}" || echo "Directory src/test/ not found."
            cp --parents -r target/ "${SONAR_SOURCES}"
        else
            echo "[TEKTON][DEBUG] Multi-module project"
            mkdir -p "${SONAR_SOURCES}/unittests"
            IFS=$'\n'
            for i in $(git diff --diff-filter=ACMR --name-only origin/"${BRANCH_NAME}")
                do cp --parents "$i" "${SONAR_SOURCES}"/
                echo "file for scanner:" "$i"/
            done
            for directory in $(find . -type d -name "test")
                do cp --parents -r ${directory} ${SONAR_SOURCES}/unittests
            done
            for poms in $(find . -type f -name "pom.xml")
                do cp --parents -r ${poms} ${SONAR_SOURCES}
            done
            for targets in $(find . -type d -name "target")
                do cp --parents -r ${targets} ${SONAR_SOURCES}
            done
        fi

        SONAR_PROJECT_KEY="${CODEBASE_NAME}-${NORMALIZED_BRANCH}:change-${CHANGE_NUMBER}-${PATCHSET_NUMBER}"

        printf "%s" "${SONAR_PROJECT_KEY}" > "$(results.SONAR_PROJECT_KEY.path)"
        printf "%s" "${SONAR_SOURCES}" > "$(results.SONAR_SOURCES.path)"
