apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitlab-create-webhooks
spec:
  params:
    - name: GitLabDomain
      default: ""
    - name: GitLabRepo
      default: ""
    - name: ExternalDomain
      default: ""

  tasks:
    - name: create-webhook
      taskRef:
        kind: Task
        name: gitlab-create-webhook
      params:
        - name: GitLabDomain
          value: $(params.GitLabDomain)
        - name: GitLabRepo
          value: $(params.GitLabRepo)
        - name: ExternalDomain
          value: $(params.ExternalDomain)

