apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitlab-create-webhook
spec:
  volumes:
    - name: gitlab-secret
      secret:
        secretName: $(params.GitLabSecretName)

  params:
    - name: ExternalDomain
      description: "The external domain for the EventListener e.g. `$(params.EventListenerName).<PROXYIP>.nip.io`"
      default: ""
    - name: GitLabRepo
      description: "The GitLab repo where the webhook will be created"
      default: ""
    - name: GitLabSecretName
      description: "The Secret name for GitLab access token. This is always mounted and must exist"
      default: "gitlab"
    - name: GitLabAccessTokenKey
      description: "The GitLab access token key name"
      default: "token"
    - name: GitLabSecretStringKey
      description: "The GitLab secret string key name"
      default: "secret"
    - name: GitLabDomain
      description: "The GitLab domain. Override for GitLab Enterprise"
      default: "gitlab.com"
  steps:
    - name: create-webhook
      image: curlimages/curl:7.85.0@sha256:f4821d304c3d1fa06dcea4feb2be79f98ff012a8fa3a51943b94e333f69b0098
      volumeMounts:
        - name: gitlab-secret
          mountPath: /var/secret
      command:
        - sh
      args:
        - -ce
        - |
          set -e
          set -o pipefail
          echo "Create Webhook"

          PROJECT_ID="$(echo $(params.GitLabRepo) | sed 's/\//%2F/g')"
          TOKEN="$(cat /var/secret/$(params.GitLabAccessTokenKey))"
          curl --fail -L -d "{\"merge_requests_events\": true,\"push_events\": false,\"token\": \"$(cat /var/secret/$(params.GitLabSecretStringKey))\"}" \
            -X POST -H "PRIVATE-TOKEN: ${TOKEN}" -H "Content-Type: application/json" \
            "https://$(params.GitLabDomain)/api/v4/projects/${PROJECT_ID}/hooks?url=https://$(params.ExternalDomain)"
