apiVersion: triggers.tekton.dev/v1alpha1
kind: Interceptor
metadata:
  name: edp
  labels:
    server/type: https
    {{- include "edp-tekton-interceptor.labels" . | nindent 4 }}
spec:
  clientConfig:
    service:
      name: tekton-triggers-edp-interceptor
      namespace: {{ .Release.Namespace }}
      port: 8443
