{{ if .Values.kaniko.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edp-kaniko
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.kaniko.roleArn }}
{{ end }}
